### ISSUE TITLE
Any possible for custom `interpolate`?

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-lodash-template#246]
```ts
export const TEMPLATE_OPTIONS: TemplateOptions = Object.freeze({
  interpolate: /{{([\S\s]+?)}}/g,
});
```

We prefer `{{  }}` over `<% %>`

**Comment by ota-meshi** [comment]
Yes. I think you can do that with parserOptions.

https://github.com/ota-meshi/eslint-plugin-lodash-template#customize-parser

**Comment by JounQin** [comment]
Nice, didn't find that, thanks!
