### ISSUE TITLE
Use eslint-plugin-lodash-template with eslint-plugin-svelte

### ISSUE THREAD

**Issue by broooke** [ota-meshi/eslint-plugin-lodash-template#250]
How can i use eslint-plugin-lodash-template with eslint-plugin-svelte? I can configured for script tag, but in html i got the parsing error.

    parser: '@typescript-eslint/parser',
    parserOptions: {
        extraFileExtensions: [
            '.svelte'
        ],
    },
    plugins: [
        '@bx-fe/svelte2',
        '@bx-fe/ts',
    ],
    extends: [
        'plugin:@bx-fe/svelte2/base',
        'plugin:@bx-fe/ts/base',
    ],
    overrides: [
        {
            files: ['*.svelte'],
            parser: 'svelte-eslint-parser',
            parserOptions: {
                parser: '@typescript-eslint/parser',
            },
            rules: rules$1
        }
    ]
    
    

This is my config before i added the eslint-plugin-lodash-template. I thought that i need to edit first object in overrides. But how i can do it correct? I also have some rules which i wrote on  eslint-plugin-svelte and i need that this rules work correct.

**Comment by ota-meshi** [comment]
This plugin uses its own custom parser to parse the templates. So plugins like svelte or vue that use another custom parser cannot be used with it.
