### ISSUE TITLE
[feature request] Support linting javascript with templates

### ISSUE THREAD

**Issue by rchl** [ota-meshi/eslint-plugin-lodash-template#95]
It seems that this plugin is only configured to work with `*.html` files. In Nuxt framework, it's common to have javascript (`*.js`) files with templates that are processed on building app.

In theory there is a way to [force this plugin to parse and lint *.js files](https://github.com/ota-meshi/eslint-plugin-lodash-template#customize-target-extentions), but then only the part inside templates is linted and not any of the surrounding javascript code.

Is it feasible to support linting *.js files with templates? I guess it might be tricky as non-template code can be essentially invalid without templates having been processed with actual data...

Relevant issue in Nuxt module where I would want to use the plugin: https://github.com/nuxt-community/nuxt-i18n/issues/415

**Comment by ota-meshi** [comment]
Thank you for this issue.

I like that idea of ​​you. 

However, linting both JavaScript inside and outside the template syntax requires big changes.
Also, there is no good idea for now how to handle JavaScript broken by templates.

```erb
<% if (a) { %>
const v = 'A'
<% } else { %>
const v = 'B'
<% } %>
```

So I can't start working right away.

---

I saw the file you want to lint.
https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/main.js

Maybe you can solve many of your problems with the following plugin:

https://github.com/mogix/eslint-plugin-ignore-erb

This plugin seems to be a plugin for ERB, but uses a similar syntax and may be available.

Set it to eslintrc as follows and force it to use `js` as well.

```js
  "overrides": [
      {
          "files": ["src/plugins/*.*"],
          plugins: [
            "ignore-erb-mogix"
          ],
          "processor": "ignore-erb-mogix/.erb"
      }
  ]
```

**Comment by rchl** [comment]
That's for answer and your suggestion.

`eslint-plugin-ignore-erb-mogix` does seem like a decent solution. Depending on the code, I will get various warnings like for example `no-unused-vars` but I can ignore those per-file. Also, some eslint warnings/errors are misaligned because they happen in processed code which doesn't match visible code. But overall I think I could work with that.

More annoying problem is that I can't really disable typescript checker that my editor is running. It seems like `// @ts-nocheck` is ignored when file has parsing error (problem like https://github.com/Microsoft/vscode/issues/66017 but for JS files). But that's off topic.

I agree that fixing this properly is probably not feasible as file can't be processed in meaningful way without having template data. Thus I'm fine with you closing this issue. Thanks for the help.
